### ISSUE TITLE
See API comments

### ISSUE THREAD

**Issue by VirtualDOMinic** [FAC-Sixteen/sylvia-sam-game#12]
I first had a peek at the API (I got lost - was very confusing when there was no React there) so left a couple of issues in there :)

https://github.com/starsuit/neopets

**Comment by tloth** [comment]
You made an API, though! Damn! :baby_chick:

**Comment by starsuit** [comment]
[It's.... beautiful](https://github.com/starsuit/neopets/issues/1)

**Comment by starsuit** [comment]
"dying is fun too" lol

**Comment by starsuit** [comment]
✨ 💃 thanks all!
